name: Build and deploy b-cal

on:
  push:
    branches:
      - main

  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
      - name: Install dependencies
        run: npm ci
      - name: Build b-cal
        run: npx nx build b-cal-web
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P b-cal --only hosting --config firebase.b-cal-web.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
